resolver: lts-15.11
allow-newer: true
extra-package-dbs: []
flags:
  generic-deriving:
    base-4-9: false
  semigroups:
    bytestring-builder: false
packages:
- '.'
extra-deps:
- snap-1.1.3.0
- heist-1.1.0.1
- map-syntax-0.3
- pwstore-fast-2.4.4
- xmlhtml-0.2.5.2
